package game;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ammo.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Ammo extends Item
{
}
