package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Bear.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Bear
{
	public void moved(Tile t)
	{
	}
}
