package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Board.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Board
{
	private Bear bear;
	public void initBoard(File setup)
	{
	}
	
	public void createTiles(File setup)
	{
	}
	
	public void generateItems(File setup)
	{
	}
	
	public void spawnPieces(File setup)
	{
	}
}
