package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Board.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//

import java.io.File;
import java.util.ArrayList;

public class Board
{
	private ArrayList<Piece> pieces;
	private ArrayList<Tile> tiles;
	private ArrayList<Item> items;
	private Bear bear;
	
	public void initBoard(File setup)
	{
	}
	
	public void createTiles(String confTiles)
	{
	}
	
	public void generateItems(String confItems)
	{
	}
	
	public void spawnPieces(String confPieces)
	{
	}
}
