package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : EndGameListner.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class EndGameListner
{
	public void notifyPlayerDied(Piece p)
	{
	}
	
	public void notifyWin()
	{
	}
}
