package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Explorer.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Explorer extends Piece
{
	public void ability(Tile t)
	{
	}
	
	public void ability(Tile t)
	{
	}
}
