package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Flare.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Flare extends Item
{
}
