package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Food.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Food implements Item
{
	public void used(Piece p)
	{
	}
}
