package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//

import java.util.ArrayList;

//singletonná kell tenni, idk how
public class Game
{
	private int nOfPlayers;
	private ArrayList<Player> players;
	private Board board;
	
	public void startGame()
	{
	}
	
	public void endGame(boolean win)
	{
	}
	
	public void notifyPlayerDied(Piece p)
	{
	}
	
	public void notifyWin()
	{
	}
	
	public void moveBear()
	{		
	}
	
	public void readFile(String s)
	{
	}
	
	public void snowStorm()
	{
	}
}
