package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Game implements EndGameListner
{
	private int nOfPlayers;
	public void startGame()
	{
	}
	
	public void endGame(boolean win)
	{
	}
	
	public void notifyPlayerDied(Piece p)
	{
	}
	
	public void notifyWin()
	{
	}
	
	public void readFile(String s)
	{
	}
	
	public void snowStorm()
	{
	}
}
