package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Hole.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Hole extends Tile
{
	private boolean covered;
	public void movedOn(Player p)
	{
	}
}
