package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ice.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Ice extends Tile
{
	private Item item;
	
	public void movedOn(Player p)
	{
	}
	
	public Item getItem()
	{
		return item;
	}
}
