package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public interface Item
{
	public void used(Piece p);
}
