package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Item.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Item
{
	private Piece items;
	public void used(Piece p)
	{
	}
}
