package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Menu.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Menu
{
	public int nOfPlayers;
	public void Operation1()
	{
	}
}
