package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Player.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Player
{
	private Piece piece;
	private Colour colour;
	
	public void move(Tile t)
	{
	}
	
	public void useItem(Item i)
	{
	}
	
	public void useAbility(Tile t)
	{
	}
	
	public void pickUpItem(Tile t)
	{
	}
}
