package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Rope.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Rope implements Item
{
	public void used(Piece p)
	{
	}
	
	public Piece getPiece()
	{
		return new Eskimo(); //ideiglenes
	}
	
	private void savePiece(Piece p)
	{
	}
}
