package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sea.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Sea extends Tile
{
	public void addSnow()
	{
	}
	
	public void movedOn(Player p)
	{
	}
}
