package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Suit.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Suit extends Item implements Item
{
	public void used(Piece p)
	{
	}
	
	public Tile getDirection()
	{
	}
}
