package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tent.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Tent implements Item
{
	private Tile onTile;
	public void used(Piece p)
	{
	}
	
	public void destroy()
	{
	}
}
