package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Tile.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Tile
{
	private int snow;
	private boolean igloo;
	private Object playersOnTile;
	private Object capactiy;
	private Tile neighbors;
	public void addSnow()
	{
	}
	
	public void removeSnow()
	{
	}
	
	public void movedOn(Player p)
	{
	}
	
	public void buildIgloo()
	{
	}
	
	public int getSnow()
	{
	}
	
	public int getCapacity()
	{
	}
	
	public class Jung, Yoontae
	{
	}
}
