package game;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Unstable.java
//  @ Date : 2020. 04. 22.
//  @ Author : 
//
//




public class Unstable extends Ice
{
	public void movedOn(Player p)
	{
	}
	
	public void flip()
	{
	}
}
