package graphics;

import javax.swing.ImageIcon;
public class NetBeansCopy extends javax.swing.JFrame {

	    ImageIcon lyuk;
	    /**
	     * Creates new form nhbv
	     */
	    public NetBeansCopy() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {
	        java.awt.GridBagConstraints gridBagConstraints;

	        buttonGroup1 = new javax.swing.ButtonGroup();
	        left = new javax.swing.JPanel();
	        jRadioButton1 = new javax.swing.JRadioButton();
	        jRadioButton2 = new javax.swing.JRadioButton();
	        jRadioButton3 = new javax.swing.JRadioButton();
	        jRadioButton4 = new javax.swing.JRadioButton();
	        jRadioButton5 = new javax.swing.JRadioButton();
	        right = new javax.swing.JPanel();
	        center = new javax.swing.JPanel();
	        jLabel1 = new javax.swing.JLabel();
	        jLabel2 = new javax.swing.JLabel();
	        jLabel3 = new javax.swing.JLabel();
	        jLabel4 = new javax.swing.JLabel();
	        jLabel5 = new javax.swing.JLabel();
	        jLabel6 = new javax.swing.JLabel();
	        jLabel7 = new javax.swing.JLabel();
	        jLabel8 = new javax.swing.JLabel();
	        jLabel9 = new javax.swing.JLabel();
	        jLabel10 = new javax.swing.JLabel();
	        jLabel11 = new javax.swing.JLabel();
	        jLabel12 = new javax.swing.JLabel();
	        jLabel13 = new javax.swing.JLabel();
	        jLabel14 = new javax.swing.JLabel();
	        jLabel15 = new javax.swing.JLabel();
	        jLabel16 = new javax.swing.JLabel();
	        jLabel17 = new javax.swing.JLabel();
	        jLabel18 = new javax.swing.JLabel();
	        jLabel19 = new javax.swing.JLabel();
	        jLabel20 = new javax.swing.JLabel();
	        jLabel21 = new javax.swing.JLabel();
	        jLabel22 = new javax.swing.JLabel();
	        jLabel23 = new javax.swing.JLabel();
	        jLabel24 = new javax.swing.JLabel();
	        jLabel25 = new javax.swing.JLabel();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        buttonGroup1.add(jRadioButton1);
	        jRadioButton1.setText("Move");

	        buttonGroup1.add(jRadioButton2);
	        jRadioButton2.setText("Ability");
	        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jRadioButton2ActionPerformed(evt);
	            }
	        });

	        buttonGroup1.add(jRadioButton3);
	        jRadioButton3.setText("Use Item");

	        buttonGroup1.add(jRadioButton4);
	        jRadioButton4.setText("Dig");

	        buttonGroup1.add(jRadioButton5);
	        jRadioButton5.setText("Pick up Item");
	        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jRadioButton5ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
	        left.setLayout(leftLayout);
	        leftLayout.setHorizontalGroup(
	            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(leftLayout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jRadioButton1)
	                    .addComponent(jRadioButton2)
	                    .addComponent(jRadioButton3)
	                    .addComponent(jRadioButton4)
	                    .addComponent(jRadioButton5))
	                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	        );
	        leftLayout.setVerticalGroup(
	            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout.createSequentialGroup()
	                .addGap(58, 58, 58)
	                .addComponent(jRadioButton1)
	                .addGap(18, 18, 18)
	                .addComponent(jRadioButton2)
	                .addGap(18, 18, 18)
	                .addComponent(jRadioButton3)
	                .addGap(18, 18, 18)
	                .addComponent(jRadioButton4)
	                .addGap(18, 18, 18)
	                .addComponent(jRadioButton5)
	                .addGap(62, 62, 62))
	        );

	        getContentPane().add(left, java.awt.BorderLayout.LINE_START);

	        javax.swing.GroupLayout rightLayout = new javax.swing.GroupLayout(right);
	        right.setLayout(rightLayout);
	        rightLayout.setHorizontalGroup(
	            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 105, Short.MAX_VALUE)
	        );
	        rightLayout.setVerticalGroup(
	            rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGap(0, 307, Short.MAX_VALUE)
	        );

	        getContentPane().add(right, java.awt.BorderLayout.LINE_END);

	        center.setPreferredSize(new java.awt.Dimension(300, 300));
	        center.setLayout(new java.awt.GridBagLayout());

	        //jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/fkhjg/iceHole_v2.png"))); // NOI18N
	        jLabel1.setText("jLabel1");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 0;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel1, gridBagConstraints);

	        jLabel2.setText("jLabel2");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 0;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel2, gridBagConstraints);

	        jLabel3.setText("jLabel3");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 0;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel3, gridBagConstraints);

	        jLabel4.setText("jLabel4");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 0;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel4, gridBagConstraints);

	        jLabel5.setText("jLabel5");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 0;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel5, gridBagConstraints);

	        jLabel6.setText("jLabel1");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 1;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel6, gridBagConstraints);

	        jLabel7.setText("jLabel2");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 1;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel7, gridBagConstraints);

	        jLabel8.setText("jLabel3");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 1;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel8, gridBagConstraints);

	        jLabel9.setText("jLabel4");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 1;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel9, gridBagConstraints);

	        jLabel10.setText("jLabel5");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 1;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel10, gridBagConstraints);

	        jLabel11.setText("jLabel1");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 2;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel11, gridBagConstraints);

	        jLabel12.setText("jLabel2");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 2;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel12, gridBagConstraints);

	        jLabel13.setText("jLabel3");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 2;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel13, gridBagConstraints);

	        jLabel14.setText("jLabel4");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 2;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel14, gridBagConstraints);

	        jLabel15.setText("jLabel5");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 2;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel15, gridBagConstraints);

	        jLabel16.setText("jLabel1");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 3;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel16, gridBagConstraints);

	        jLabel17.setText("jLabel2");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 3;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel17, gridBagConstraints);

	        jLabel18.setText("jLabel3");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 3;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel18, gridBagConstraints);

	        jLabel19.setText("jLabel4");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 3;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel19, gridBagConstraints);

	        jLabel20.setText("jLabel5");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 3;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel20, gridBagConstraints);

	        jLabel21.setText("jLabel1");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 4;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel21, gridBagConstraints);

	        jLabel22.setText("jLabel2");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 4;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel22, gridBagConstraints);

	        jLabel23.setText("jLabel3");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 4;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel23, gridBagConstraints);

	        jLabel24.setText("jLabel4");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 4;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel24, gridBagConstraints);

	        jLabel25.setText("jLabel5");
	        gridBagConstraints = new java.awt.GridBagConstraints();
	        gridBagConstraints.gridy = 4;
	        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
	        gridBagConstraints.weightx = 1.0;
	        gridBagConstraints.weighty = 1.0;
	        center.add(jLabel25, gridBagConstraints);

	        getContentPane().add(center, java.awt.BorderLayout.CENTER);

	        pack();
	    }// </editor-fold>                        

	    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                              
	        // TODO add your handling code here:
	    }                                             

	    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
	        // TODO add your handling code here:
	    }                                             

	    /**
	     * @param args the command line arguments
	     */
	   /* public static void main(String args[]) {
	        
	        try {
	            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
	                if ("Nimbus".equals(info.getName())) {
	                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
	                    break;
	                }
	            }
	        } catch (ClassNotFoundException ex) {
	            java.util.logging.Logger.getLogger(NetBeansCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (InstantiationException ex) {
	            java.util.logging.Logger.getLogger(NetBeansCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (IllegalAccessException ex) {
	            java.util.logging.Logger.getLogger(NetBeansCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	            java.util.logging.Logger.getLogger(NetBeansCopy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	        }
	        //</editor-fold>
	        //</editor-fold>

	        java.awt.EventQueue.invokeLater(new Runnable() {
	            public void run() {
	                new NetBeansCopy().setVisible(true);
	            }
	        });
	    }*/

	    // Variables declaration - do not modify                     
	    private javax.swing.ButtonGroup buttonGroup1;
	    private javax.swing.JPanel center;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel10;
	    private javax.swing.JLabel jLabel11;
	    private javax.swing.JLabel jLabel12;
	    private javax.swing.JLabel jLabel13;
	    private javax.swing.JLabel jLabel14;
	    private javax.swing.JLabel jLabel15;
	    private javax.swing.JLabel jLabel16;
	    private javax.swing.JLabel jLabel17;
	    private javax.swing.JLabel jLabel18;
	    private javax.swing.JLabel jLabel19;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel20;
	    private javax.swing.JLabel jLabel21;
	    private javax.swing.JLabel jLabel22;
	    private javax.swing.JLabel jLabel23;
	    private javax.swing.JLabel jLabel24;
	    private javax.swing.JLabel jLabel25;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    private javax.swing.JLabel jLabel6;
	    private javax.swing.JLabel jLabel7;
	    private javax.swing.JLabel jLabel8;
	    private javax.swing.JLabel jLabel9;
	    private javax.swing.JRadioButton jRadioButton1;
	    private javax.swing.JRadioButton jRadioButton2;
	    private javax.swing.JRadioButton jRadioButton3;
	    private javax.swing.JRadioButton jRadioButton4;
	    private javax.swing.JRadioButton jRadioButton5;
	    private javax.swing.JPanel left;
	    private javax.swing.JPanel right;
	    // End of variables declaration                   
}

